### ISSUE TITLE
Post run error

### ISSUE THREAD

**Issue by miaomucheng1** [XinRanZh/ProjectAim-ApexLegends#4]
I don't know why after running
Tips：
Fusing layers...
Model Summary: 224 layers, 7056607 parameters, 0 gradients
Traceback (most recent call last):
  File "ProjectAim-ApexLegends-main\main.py", line 168, in <module>
    main()
  File "ProjectAim-ApexLegends-main\main.py", line 165, in main
    detect(opt)
  File "Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "ProjectAim-ApexLegends-main\main.py", line 84, in detect
    window_capture("game.jpg", windowsid)
  File "ProjectAim-ApexLegends-main\main.py", line 27, in window_capture
    rect = win32gui.GetWindowRect(hwnd)
pywintypes.error: (1400, 'GetWindowRect', '无效的窗口句柄。')

**Comment by windictbo** [comment]
Dude，I get the same problem，how did you solve this problem？

**Comment by meguminsuki** [comment]
同样的问题，如何解决这个问题呢
